name: Build dylib
on: [push, pull_request]  # 确保触发条件包含 push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "export THEOS=~/theos" >> ~/.bashrc
          echo "export PATH=$PATH:~/theos/bin" >> ~/.bashrc
          source ~/.bashrc

      - name: Build tweak
        run: |
          cd $GITHUB_WORKSPACE
          make package

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: WeChatTweak.dylib
          path: .theos/obj/debug/*.dylib
