name: Build dylib
on: [push, workflow_dispatch]  # 支持推送触发和手动触发

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "export THEOS=~/theos" >> ~/.bashrc
          echo "export PATH=$PATH:~/theos/bin" >> ~/.bashrc

      - name: Build tweak
        run: |
          source ~/.bashrc
          cd $GITHUB_WORKSPACE
          make package

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: WeChatTweak.dylib
          path: .theos/obj/debug/*.dylib
