name: WeChatTweak CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 20
    env:
      THEOS: ${{ github.workspace }}/theos  # 关键修改点
      SDKVERSION: 16.4

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 设置 Theos 环境并安装依赖
    - name: Setup Theos and Install Dependencies
      run: |
        # 克隆并更新 Theos
        git clone --filter=blob:none --depth 1 \
          https://github.com/theos/theos.git $THEOS
        $THEOS/bin/update-theos
        # 安装 Xcode 命令行工具
        xcode-select --install

    # 构建 .deb 包
    - name: Build Tweak Package
      run: |
        export PATH="$THEOS/bin:$PATH"
        make clean
        make package \
          THEOS_PACKAGE_SCHEME=rootless \
          DEBUG=0 \
          CODESIGNING_ALLOWED=NO

    # 上传构建的 .deb 包
    - name: Upload .deb Artifact
      uses: actions/upload-artifact@v4
      with:
        name: WeChatTweak_${{ github.run_number }}
        path: packages/*.deb
