name: WeChatTweak CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: macos-latest  # 关键修改点
    timeout-minutes: 25
    env:
      THEOS: ${{ github.workspace }}/theos

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Theos
      run: |
        git clone --depth 1 https://github.com/theos/theos.git $THEOS
        echo "THEOS=$THEOS" >> $GITHUB_ENV

    - name: Build
      run: |
        export PATH="$THEOS/bin:$PATH"
        make package DEBUG=0
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: WeChatTweak
        path: packages/*.deb
